POST http://localhost:3000/signup
Content-Type: application/json

{
    "Name": "Amos Mwongela",
    "Email": "am@gmail.com",
    "Password": "h5kjfhjhhjhfgvb",
    "Role": "Admin",
    "isAssigned": false
}

###
POST http://localhost:3002/users/signup
Content-Type: application/json

{
    "Name": "Amos Mwongela",
    "Email": "amos@gmail.com",
    "Password": "1to34567",
    "Role": "Admin",
    "isAssigned": false
}


###
POST http://localhost:3002/users/login/
Content-Type: application/json

{
    "Email": "amosmwongelah@gmail.com",
    "Password": "Lethal 23"
}

###
GET http://localhost:3002/users/check
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6ImU3MTlhYWM5LWE5NmEtNDYzZS05ZjBhLWE5NmMyY2NkNzUxZCIsIk5hbWUiOiJBbW9zIE13b25nZWxhIiwiRW1haWwiOiJhbW9zbXdvbmdlbGFoQGdtYWlsLmNvbSIsIlJvbGUiOiJBZG1pbiIsImlzQXNzaWduZWQiOjAsImlhdCI6MTY2MDQ2ODIzNiwiZXhwIjoxNjYwNDcxODM2fQ.YiET5jwEz4meIxlSujI1NYiHu86ohVi_WSN74wyLyqM"
}

###
POST http://localhost:3002/projects/
Content-Type: application/json

{
    "ProjectName": "Export CSv files IN Excell",
    "Description": "On the Data tab, in the Get & Transform Data group, click From Text/CSV",
    "Due_date": "2022/09/01",
    "User": "Amos Mwongela"
}
